export const BRIDGE_SOURCE = String.raw`#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');const cp=require('node:child_process');
const MAX_OUTPUT=16384;
const ALIASES={bash:'Bash',powershell:'Bash',view:'Read',read:'Read',create:'Write',write:'Write',edit:'Edit',str_replace_editor:'Edit',apply_patch:'Edit',grep:'Grep',rg:'Grep',glob:'Glob',web_fetch:'WebFetch',web_search:'WebSearch',ask_user:'AskUserQuestion',update_todo:'TodoWrite',task:'Agent'};
const OPS={'session-start':['session-init.cjs','dev-rules-reminder.cjs'],'subagent-start':['subagent-init.cjs'],'pre-tool-use':['scout-block.cjs','privacy-block.cjs'],'scout-block':['scout-block.cjs'],'privacy-block':['privacy-block.cjs'],'post-tool-use':['modularization-hook.js'],'pre-compact':['write-compact-marker.cjs'],'session-end':['session-end.cjs']};
function fail(message,code){process.stderr.write('Copilot hook bridge: '+message+'\\n');return code||2;}
function readPayload(){const raw=fs.readFileSync(0,'utf8').trim();if(!raw)return {};const value=JSON.parse(raw);if(!value||typeof value!=='object'||Array.isArray(value))throw Error('hook payload must be a JSON object');return value;}
function first(){for(const value of arguments)if(typeof value==='string'&&value)return value;return undefined;}
function parseInput(value){if(typeof value!=='string')return value;try{return JSON.parse(value);}catch{return value;}}
function payload(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('hook payload must be a JSON object');const toolInput=input.tool_input!==undefined?input.tool_input:input.toolInput!==undefined?input.toolInput:input.toolArgs!==undefined?input.toolArgs:input.input;const toolName=first(input.tool_name,input.toolName,input.tool&&input.tool.name);return {...input,cwd:first(input.cwd,input.workingDirectory,input.working_directory)||process.cwd(),session_id:first(input.session_id,input.sessionId,input.session&&input.session.id),agent_type:first(input.agent_type,input.agentType,input.agentName,input.agentDisplayName,input.agent&&input.agent.type,input.agent&&input.agent.name),agent_id:first(input.agent_id,input.agentId,input.agent&&input.agent.id),tool_name:typeof toolName==='string'?(ALIASES[toolName.toLowerCase()]||toolName):undefined,tool_input:parseInput(toolInput),transcript_path:first(input.transcript_path,input.transcriptPath),source:first(input.source,input.reason,input.trigger)||'unknown'};}
function validate(operation,value){if(!['pre-tool-use','scout-block','privacy-block','post-tool-use'].includes(operation))return;if(typeof value.tool_name!=='string'||!value.tool_name.trim())throw Error(operation+' payload requires a tool name');if(!value.tool_input||typeof value.tool_input!=='object'||Array.isArray(value.tool_input))throw Error(operation+' payload requires an object tool input');}
function childOutput(value){const text=String(value||'').trim();if(!/^[{\\[]/.test(text))return text;let parsed;try{parsed=JSON.parse(text);}catch(error){throw Error('child emitted malformed JSON: '+error.message);}const candidate=parsed&&parsed.hookSpecificOutput&&parsed.hookSpecificOutput.additionalContext!==undefined?parsed.hookSpecificOutput.additionalContext:parsed&&parsed.additionalContext;if(typeof candidate==='string')return candidate.trim();if(Array.isArray(candidate)&&candidate.every(item=>typeof item==='string'))return candidate.join('\\n').trim();throw Error('child JSON omitted additionalContext');}
function safeCwd(value){if(typeof value!=='string'||!path.isAbsolute(value))return process.cwd();try{const stat=fs.lstatSync(value);return stat.isDirectory()&&!stat.isSymbolicLink()?value:process.cwd();}catch{return process.cwd();}}
function hasSymlinkedPathComponent(candidate){let current=path.resolve(candidate);while(true){try{if(fs.lstatSync(current).isSymbolicLink())return true;}catch{return true;}const parent=path.dirname(current);if(parent===current)return false;current=parent;}}
function safeChild(candidate){try{const stat=fs.lstatSync(candidate);return stat.isFile()&&!stat.isSymbolicLink()&&!hasSymlinkedPathComponent(candidate);}catch{return false;}}
function runOperation(operation,input){const scripts=OPS[operation];if(!scripts)return fail('unsupported operation: '+operation);let value;try{value=payload(input===undefined?readPayload():input);validate(operation,value);}catch(error){return fail(error.message);}const resourceRoot=path.resolve(__dirname,'..');const configRoot=path.dirname(resourceRoot);const cwd=safeCwd(value.cwd);const env={...process.env,COPILOT_HOME:process.env.COPILOT_HOME||configRoot,EVCRATE_CONFIG_DIR:'.copilot',EVCRATE_GLOBAL_CONFIG_ROOT:configRoot,EVCRATE_RESOURCE_ROOT:resourceRoot,CLAUDE_PROJECT_DIR:cwd,COPILOT_PROJECT_DIR:cwd};delete env.CLAUDE_ENV_FILE;if(value.session_id)env.EVCRATE_SESSION_ID=value.session_id;const contexts=[];for(const script of scripts){const child=path.join(__dirname,script);if(!safeChild(child))return fail('missing hook script: '+script,127);const result=cp.spawnSync(process.execPath,[child],{cwd:cwd,env:env,input:JSON.stringify(value),encoding:'utf8',windowsHide:true});if(result.error)return fail(result.error.message,127);if(result.stderr)process.stderr.write(result.stderr);if(result.status!==0)return result.status||1;try{const context=childOutput(result.stdout);if(context)contexts.push(context);}catch(error){return fail(error.message);}}const context=contexts.join('\\n\\n').trim().slice(0,MAX_OUTPUT);if(context)process.stdout.write(JSON.stringify({additionalContext:context})+'\\n');return 0;}
function main(){try{process.exitCode=runOperation(process.argv[2],readPayload());}catch(error){process.exitCode=fail(error.message);}}
module.exports=runOperation;module.exports.OPERATIONS=OPS;module.exports.canonicalPayload=payload;module.exports.childOutput=childOutput;if(require.main===module)main();
`;
